access_points: ['nextgenio-cn28']
port: 10001
transport_config:
  allow_insecure: true
  client_cert_dir: /etc/daos/certs/clients
  ca_cert: /etc/daos/certs/daosCA.crt
  cert: /etc/daos/certs/server.crt
  key: /etc/daos/certs/server.key
provider: ofi+tcp;ofi_rxm
hyperthreads: true
socket_dir: /tmp/daos/run/daos_server
control_log_file: /tmp/daos/log/daos_control.log
helper_log_file: /tmp/daos/log/daos_admin.log
engines:
-
  targets: 12
  fabric_iface: ib0
  fabric_iface_port: 21000
  pinned_numa_node: 0
  log_file: /tmp/daos/log/daos_server1.log
  env_vars:
  - CRT_TIMEOUT=30
  - CRT_CREDIT_EP_CTX=0
  - FI_TCP_MAX_CONN_RETRY=1
  - FI_TCP_CONN_TIMEOUT=2000
  - CRT_PHY_ADDR_STR="ofi+tcp;ofi_rxm"
  - DAOS_MD_CAP=2048
  scm_mount: /mnt/daos/1
  scm_class: dcpm
  scm_list: [/dev/pmem0]
-
  targets: 12
  fabric_iface: ib1
  fabric_iface_port: 21500
  pinned_numa_node: 1
  log_file: /tmp/daos/log/daos_server2.log
  env_vars:
  - CRT_TIMEOUT=30
  - CRT_CREDIT_EP_CTX=0
  - FI_TCP_MAX_CONN_RETRY=1
  - FI_TCP_CONN_TIMEOUT=2000
  - CRT_PHY_ADDR_STR="ofi+tcp;ofi_rxm"
  - DAOS_MD_CAP=2048
  scm_mount: /mnt/daos/2
  scm_class: dcpm
  scm_list: [/dev/pmem1]
