access_points: ['nextgenio-cn01']
port: 10001
transport_config:
  allow_insecure: true
  client_cert_dir: /etc/daos/certs/clients
  ca_cert: /etc/daos/certs/daosCA.crt
  cert: /etc/daos/certs/server.crt
  key: /etc/daos/certs/server.key
provider: ofi+tcp;ofi_rxm
hyperthreads: true
socket_dir: /tmp/daos/run/daos_server
control_log_file: /tmp/daos/log/daos_control.log
helper_log_file: /tmp/daos/log/daos_admin.log
telemetry_port: 9191
engines:
-
  targets: 12
  fabric_iface: ib0
  fabric_iface_port: 32000
  pinned_numa_node: 0
  log_file: /tmp/daos/log/daos_server1.log
  env_vars:
#  - LD_LIBRARY_PATH=/home/software/psm2/11.2.228/usr/lib64:/home/software/libfabric/latest/lib:$LD_LIBRARY_PATH
#  - LD_LIBRARY_PATH=/home/software/libfabric/latest/lib:$LD_LIBRARY_PATH
#  - LD_LIBRARY_PATH=/home/software/libfabric/opx-beta:$LD_LIBRARY_PATH
#  - LD_LIBRARY_PATH=/usr/lib:/usr/lib64/:$LD_LIBRARY_PATH
#  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/prereq/release/spdk/lib
  - CRT_TIMEOUT=30
  - CRT_CREDIT_EP_CTX=0
  - FI_TCP_MAX_CONN_RETRY=1
  - FI_TCP_CONN_TIMEOUT=2000
  - DAOS_MD_CAP=2048
  - CRT_PHY_ADDR_STR="ofi+tcp;ofi_rxm"
  - FI_PROVIDER=tcp
  - FI_TCP_IFACE=ib0
  - FI_TCP_BIND_BEFORE_CONNECT=1
  - FI_OFI_RXM_DEF_TCP_WAIT_OBJ=pollfd
  - ABT_THREAD_STACKSIZE=32768
  scm_mount: /mnt/daos/1
  scm_class: dcpm
  scm_list: [/dev/pmem0]
-
  targets: 12
  fabric_iface: ib1
  fabric_iface_port: 32500
  pinned_numa_node: 1
  log_file: /tmp/daos/log/daos_server2.log
  env_vars:
#  - LD_LIBRARY_PATH=/home/software/psm2/11.2.228/usr/lib64:/home/software/libfabric/latest/lib:$LD_LIBRARY_PATH
#  - LD_LIBRARY_PATH=/home/software/libfabric/latest/lib:$LD_LIBRARY_PATH
#  - LD_LIBRARY_PATH=/home/software/libfabric/opx-beta:$LD_LIBRARY_PATH
#  - LD_LIBRARY_PATH=/usr/lib:/usr/lib64/:$LD_LIBRARY_PATH
#  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/prereq/release/spdk/lib
  - CRT_TIMEOUT=30
  - CRT_CREDIT_EP_CTX=0
  - FI_TCP_MAX_CONN_RETRY=1
  - FI_TCP_CONN_TIMEOUT=2000
  - DAOS_MD_CAP=2048
  - CRT_PHY_ADDR_STR="ofi+tcp;ofi_rxm"
  - FI_PROVIDER=tcp
  - FI_TCP_IFACE=ib1
  - FI_TCP_BIND_BEFORE_CONNECT=1
  - FI_OFI_RXM_DEF_TCP_WAIT_OBJ=pollfd
  - ABT_THREAD_STACKSIZE=32768
  scm_mount: /mnt/daos/2
  scm_class: dcpm
  scm_list: [/dev/pmem1]
